### PR TITLE
Add perfomance check btwn master pr [2]

### PR DESCRIPTION
**Pull request by RaulTrombin**
We need:

- [x] https://github.com/bluerobotics/navigator-rs/actions/runs/6793108897
- [x] check failure due performance decrease & remove last commit

### CODE REVIEW

**Comment by RaulTrombin** [comment]
@patrickelectric We need to re-run the last master's action jobs.
It was missing tree on the new self-hosted device.

- [ ] https://github.com/bluerobotics/navigator-rs/actions/runs/6796609699/job/18477159747

**Comment by RaulTrombin** [comment]
It works:
image

Next, removing delay test commit and waiting a review @patrickelectric .

**Comment by RaulTrombin** [comment]
ping @patrickelectric

**Comment by patrickelectric** [comment]
@RaulTrombin is this wip ?

**Review by patrickelectric — APPROVED** [review]

**Pull request merged**
